name: Release

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: yarn

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: stable
                  cache: false

            - name: Install dependencies
              run: yarn install --immutable

            - name: Stage release files
              run: yarn release:stage

            # SignPath will go here later.
            #
            # It needs to run after staging and before zipping, because it must replace:
            #
            # release/wiiu-vault-windows-x64/wiiu-vault.exe
            # release/wiiu-vault-windows-arm64/wiiu-vault.exe
            #
            # with signed versions.

            - name: Zip release files
              run: yarn release:zip

            - name: Upload ZIPs as workflow artifact
              uses: actions/upload-artifact@v4
              with:
                  name: wiiu-vault-release-zips
                  path: release/wiiu-vault-*.zip
                  retention-days: 7

            - name: Create GitHub release
              if: startsWith(github.ref, 'refs/tags/')
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  gh release create "${GITHUB_REF_NAME}" ./release/wiiu-vault-*.zip \
                    --title "${GITHUB_REF_NAME}" \
                    --generate-notes \
                    --verify-tag
